//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSupplyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderIngredients
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public double IngredientPrice { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Ingredients Ingredients { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
