//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSupplyDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestSupplyDBModelContainer : DbContext
    {
        public RestSupplyDBModelContainer()
            : base("name=RestSupplyDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredients> IngredientsSet { get; set; }
        public virtual DbSet<Users> UsersSet { get; set; }
        public virtual DbSet<Suppliers> SuppliersSet { get; set; }
        public virtual DbSet<MenuItems> MenuItemsSet { get; set; }
        public virtual DbSet<Orders> OrdersSet { get; set; }
        public virtual DbSet<OrderIngredients> OrderIngredientsSet { get; set; }
        public virtual DbSet<MenuIngredients> MenuIngredientsSet { get; set; }
        public virtual DbSet<Kitchens> KitchensSet { get; set; }
        public virtual DbSet<KitchenIngredients> KitchenIngredientsSet { get; set; }
        public virtual DbSet<UserTypes> UserTypesSet { get; set; }
    }
}
