// <auto-generated />
namespace RestSupplyDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration_custom_user_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_custom_user_types));
        
        string IMigrationMetadata.Id
        {
            get { return "201901181522569_migration_custom_user_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
