// <auto-generated />
namespace RestSupplyDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class link_customer_order_details_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(link_customer_order_details_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201901261645496_link_customer_order_details_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
