// <auto-generated />
namespace RestSupplyDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_1_cascade_del_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_1_cascade_del_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201902252117379_update_1_cascade_del_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
