// <auto-generated />
namespace RestSupplyDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixed_many_to_many_supplier_ingredient_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixed_many_to_many_supplier_ingredient_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201901241604568_fixed_many_to_many_supplier_ingredient_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
